server:
  # 端口
  port: 8081
  tomcat:
    accept-count: 600
    max-connections: 10000
    threads:
      max: 500


spring:
  servlet:
    multipart:
      # 配置文件上传大小限制
      max-file-size: 10GB
      max-request-size: 10GB
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.3.66:3306/db_minioweb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: Abc123!@#
    hikari:
      # 连接池名
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 最大连接数，默认10
      maximum-pool-size: 10
      # 从连接池返回的连接的自动提交
      auto-commit: true
      # 连接最大存活时间，0表示永久存活，默认1800000（30分钟）
      max-lifetime: 1800000
      # 连接超时时间，默认30000（30秒）
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1
  mail:
    host: smtp.qq.com
    username: 2411767821@qq.com
    password: mhnmdfuwyaypdifc
    default-encoding: UTF-8

  redis:
    host: 192.168.3.66
    port: 6379
    timeout: 10000ms
    lettuce:
      pool:
        # 最大连接数，默认 8
        max-active: 1024
        # 最大连接阻塞等待时间，单位毫秒，默认 -1
        max-wait: 10000ms
        # 最大空闲连接，默认 8
        max-idle: 200
        # 最小空闲连接
        min-idle: 5


# Mybatis-plus配置
mybatis-plus:
  #配置Mapper映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置MyBatis数据返回类型别名
  type-aliases-package: com.minio.server.pojo
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: false


## Mybatis SQL 打印
logging:
  level:
    com.minio.server.mapper:

minio:
  #minio部署的机器ip地址
  endpoint: 60.208.15.171
  #minio使用的端口
  port: 9000
  #唯一标识的账户
  accessKey: admin
  #账户的密码
  secretKey: abc123456
  #是否使用https
  secure: false
  #测试使用的桶名称
  defaultBucketName: test
  #存储类型
  storage-type: 0

jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT 加解密使用的密钥
  secret: yeb-secret
  # JWT的超期限时间（60*60*24）
  expiration: 604800
  # JWT 负载中拿到开头
  tokenHead: Bearer


